#!/usr/bin/python3
import json
import os
import sys

if sys.argv[1:] == ["--version"]:
    print("codex-cli 0.153.4")
else:
    print(json.dumps({"pid": os.getpid(), "argv": sys.argv[1:], "stdin": sys.stdin.read(),
                      "home": os.environ["HOME"], "codexHome": os.environ["CODEX_HOME"]}))
