#!/usr/bin/env bash
# Regenerate the approved DirectTarget execution asset with the pinned native tooling,
# verify its exact bytes and native graph/runtime admission. Runs no target or provider.
# Usage: generate.sh ZEROSHOT_EXECUTABLE [OUTPUT]
set -euo pipefail

assets="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
native="$(realpath -- "${1:?Usage: generate.sh ZEROSHOT_EXECUTABLE [OUTPUT]}")"
output="${2:-}"
approved_sha256=10f410b4a3ba06f69ead07b5d281d289fd6e378854bcb0600b1d963bdfce55d8
native_sha256=afeb4372eaa63c3d88b308bd32afa5b888297fc0a82aa879542daf1437a6ee06

[[ "$(sha256sum -- "$native" | cut -d ' ' -f 1)" == "$native_sha256" ]] \
    || { printf 'The pinned Linux x86-64 zeroshot 10.3.0 executable is required.\n' >&2; exit 1; }

work="$(mktemp -d -t broodling-execution-asset.XXXXXXXX)"
trap 'rm -rf -- "$work"' EXIT
mkdir -p "$work/home" "$work/config"
zeroshot() {
    (cd -- "$work" && env -i PATH=/usr/bin:/bin HOME="$work/home" ZEROSHOT_CONFIG_DIR="$work/config" "$native" "$@")
}
[[ "$(zeroshot --version)" == 'zeroshot 10.3.0' ]]

# Asset identity is SHA-256 of these exact bytes: {graph, runtime} from `profile show`,
# written as Python json.dumps(indent=2, sort_keys=True) plus a final newline.
format='import json, sys
profile = json.load(sys.stdin)
sys.stdout.write(json.dumps({"graph": profile["graph"], "runtime": profile["runtime"]}, indent=2, sort_keys=True) + "\n")'
printf '%s\n' '{"harness":"codex","provider":"gateway","model":"gpt-5.6-sol","effort":"medium","size":"small","sessionScope":"execution"}' \
    >"$work/uniform-runtime.json"
zeroshot profile set generated --template software-change --delivery pull_request \
    --uniform-runtime-config "$work/uniform-runtime.json" >/dev/null
zeroshot profile show generated | python3 -c "$format" >"$work/asset.json"
[[ "$(sha256sum -- "$work/asset.json" | cut -d ' ' -f 1)" == "$approved_sha256" ]] \
    || { printf 'Generated bytes differ from the approved execution asset.\n' >&2; exit 1; }
cmp -- "$work/asset.json" "$assets/software-change-pr-codex-gateway.json"

# Native admission of the opaque values the application submits, with an exact round trip.
python3 -c 'import json, sys
asset = json.load(open(sys.argv[1]))
for name in ("graph", "runtime"):
    json.dump(asset[name], open(sys.argv[2] + "/" + name + ".json", "w"))' "$work/asset.json" "$work"
zeroshot profile set admitted --graph "$work/graph.json" --runtime-config "$work/runtime.json" >/dev/null
zeroshot profile show admitted | python3 -c "$format" | cmp -- "$work/asset.json" -

if [[ -n "$output" ]]; then cp -- "$work/asset.json" "$output"; fi
printf 'Verified execution asset sha256:%s and native admission.\n' "$approved_sha256"
